CREATE DATABASE recipesdb;

CREATE TABLE recipes(
	id SERIAL PRIMARY KEY,
	uid VARCHAR(255) UNIQUE NOT NULL, 
	title VARCHAR(255) NOT NULL,
	prep_time VARCHAR(255) NOT NULL,
	cook_time VARCHAR(255) NOT NULL,
	servings INT NOT NULL,
	ingredients TEXT[] NOT NULL,
	instructions TEXT[] NOT NULL,
	user_ingredients TEXT[] NOT NULL
);

ALTER TABLE recipes
ADD COLUMN uid VARCHAR(255) UNIQUE NOT NULL;

CREATE TABLE recipes2(
	id SERIAL PRIMARY KEY,
	uid VARCHAR(255) UNIQUE NOT NULL,
	title VARCHAR(255) NOT NULL,
	prep_time VARCHAR(255) NOT NULL,
	cook_time VARCHAR(255) NOT NULL,
	servings INT NOT NULL,
	ingredients TEXT[] NOT NULL,
	instructions TEXT[] NOT NULL,
	user_ingredients TEXT[] NOT NULL
);

ALTER TABLE recipes2
ADD COLUMN uid VARCHAR(255) UNIQUE NOT NULL;


CREATE TABLE ingredients(
	id SERIAL PRIMARY KEY, 
	name VARCHAR(255) NOT NULL
);

CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	user_name VARCHAR(255) NOT NULL,
	user_email VARCHAR(255) UNIQUE NOT NULL,
	user_key VARCHAR(255) UNIQUE NOT NULL,
	user_recipes VARCHAR(255)[] DEFAULT '{}'::VARCHAR(255)[],
	rate_limiter INT DEFAULT 50
);
